### ISSUE TITLE
Battery Icon Doesnt Apper

### ISSUE THREAD

**Issue by nanohelperDev** [Otus9051/Hackintosh-HP-15s-eq2144au#1]
The battery doesn't detected on laptop the same model you have , amd rayzen 5 5625u, and hp 15s-eq3XXX

**Comment by Otus9051** [comment]
It's a Ryzen 5. I have a Ryzen 3.
You have a eq3xxx. I have a eq2144au.
How did you even think this could work?
Generate your own DSDTs, you can copy the plist and kexts from here.

**Comment by nanohelperDev** [comment]
Okay thank you thats help full
