### ISSUE TITLE
Hardware encoding for AMD RAYZEN 5 XXXXU

### ISSUE THREAD

**Issue by nanohelperDev** [Otus9051/Hackintosh-HP-15s-eq2144au#2]
Hello Dear, i want ask if the Hardware encoding and H.246 working for you, cause some apps like FL Studio, Zrush, not runing depend on them, are theres away to fix thats ? Thanks in advance :)

**Comment by Otus9051** [comment]
THIS EFI IS **ONLY FOR RYZEN 3 5300U**
FOR HARDWARE ENCODING AND SHIT GO SCREAM AT NOOTEDRED
AND IT WORKS ON RYZEN 3
PLEASE DO NOT FLOOD THIS WITH RYZEN 5 SHIT
