### ISSUE TITLE
Microphone Fix

### ISSUE THREAD

**Issue by angelokimhui** [Otus9051/Hackintosh-HP-15s-eq2144au#3]
Search for the Kext "AMDMicrophone". Worked flawlessly on my EQ-3XXX. Should work with yours as well.

**Comment by angelokimhui** [comment]
![Screenshot 2024-06-17 at 6 23 38 PM](https://github.com/Otus9051/Hackintosh-HP-15s-eq2144au/assets/82715920/06298d1d-adb1-4a13-94ef-d2364d8ec82b)

Currently on Sonoma as well. 14.5.

**Comment by Otus9051** [comment]
If someone makes a PR, that would be appreciated. 
I no longer have the WiFi Adapter that I was using (Archer T2U Nano) so I don't use or update this repository much.

**Comment by Otus9051** [comment]
Re-built my EFI, this seems to work great, thanks for the advice!
Edit: I did need to use Chris1111's Kext Installer thingy, but that's about it.
